# Generated by Django 4.1 on 2022-08-08 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("drugs_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
